### ISSUE TITLE
folding in server-info rate

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#106]
--folding-level=1

```
net:
  vtep1500402:
    buffers:
      cur: 1
      max: 1
    driver: 2
    queues: 1
```

should become:

```
vtep1500402: 1
```

--folding-level=2

```
net: 1
```
