### ISSUE TITLE
server-info show thinks i40e queues are unknown, but they are combined

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#165]
```
    queues:
      own: []
      rx: []
      rxtx: []
      shared: []
      tx: []
      unknown:
      - i40e-eth3-TxRx-0
      - i40e-eth3-TxRx-1
      - i40e-eth3-TxRx-2
      - i40e-eth3-TxRx-3
      - i40e-eth3-TxRx-4
      - i40e-eth3-TxRx-5
      - i40e-eth3-TxRx-6
      - i40e-eth3-TxRx-7
```

look at i40e-bug.tar.gz @ node4.
