### ISSUE TITLE
Folding in server-info

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#180]
- [x] -f - fold device info into one rating
- [x] -ff - fold subsystem info into one rating
- [x] -fff - fold entire server info into one rating
- [x] get rid of ...

**Comment by strizhechenko** [comment]
``` yaml
➜  vscale-vm git:(folding) ✗ server-info-rate 
cpu:
  BogoMIPS: 2
  CPU MHz: 2
  CPU(s): 1
  Core(s) per socket: 1
  L3 cache: 9
  Socket(s): 1
  Thread(s) per core: 10
  Vendor ID: 10
disk:
  vda:
    size: 1
    type: 1
memory:
  devices:
    '0x1100':
      size: 1
      speed: 1
      type: 1
  size:
    MemTotal: 1
    SwapTotal: 1
net:
  eth0:
    buffers:
      cur: 1
      max: 1
    driver: 2
    queues: 1
system:
  Hypervisor vendor: 1
  Virtualization type: 1
➜  vscale-vm git:(folding) ✗ server-info-rate -f
cpu:
  BogoMIPS: 2
  CPU MHz: 2
  CPU(s): 1
  Core(s) per socket: 1
  L3 cache: 9
  Socket(s): 1
  Thread(s) per core: 10
  Vendor ID: 10
disk:
  vda: 1.0
memory:
  devices:
    '0x1100': 1.0
  size: 1.0
net:
  eth0: 1.3333333333333333
system:
  Hypervisor vendor: 1
  Virtualization type: 1
➜  vscale-vm git:(folding) ✗ server-info-rate -ff
cpu: 4.5
disk: 1.0
memory: 1.0
net: 1.3333333333333333
system: 1.0
➜  vscale-vm git:(folding) ✗ server-info-rate -fff
server: 1.7666666666666664
```
