### ISSUE TITLE
server-info should rate cur and max queues for netdev

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#194]
cur 4 max 8

``` yaml
net:
  eth0:
    buffers:
      cur: 10
      max: 10
    driver: 2
    queues: 3
```
